config/routes.rb
Rails.application.routes.draw do

  resources :shortened_urls, only: [:index, :new, :create] do
    collection do
      post 'upload_from_csv'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      #:new, :edit, :update
      namespace :features do
        resources :url_shorteners, only: [:create, :destroy, :index, :show], param: :unique_key
      end
    end
  end

  get '/:unique_key' => 'shortened_urls#redirect_handler'
  root 'shortened_urls#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortened_url.rb
class ShortenedUrl < ApplicationRecord
  before_create :generate_token
  validates_presence_of [:url, :unique_key]
  validates_uniqueness_of :unique_key

  def generate_token
    custom_key = nil
    begin
      unique_key = custom_key || UrlShortener.get_uniq_key
      custom_key = nil
    end while self.class.exists?(unique_key: unique_key) && custom_key.blank?
    self.unique_key = unique_key
  end

  def self.get_records(host)
    select(:url, :unique_key).map{ |u| u.create_json_object(host) }
  end

  def create_json_object(host)
    {url: url, short_url: UrlShortener.create_url(host, unique_key)}
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  before_action :set_headers
  include ResponseHelper
  include ExceptionHandler

  def set_headers
    response.headers['Content-Type'] = 'application/json'
  end
end

app/controllers/api/v1/features/url_shorteners_controller.rb
class Api::V1::Features::UrlShortenersController < Api::V1::BaseController
  before_action :sanitize_url, only: [:create]

  def index
    json_response(ShortenedUrl.get_records(request.host), :ok)
  end

  def create
    result = ShortenedUrl.find_or_create_by(url: @sanitized_url)
    json_response( result.create_json_object(request.host), :ok)
  end

  # for searching the origin url
  def show
    result = ShortenedUrl.find_by(unique_key: params[:unique_key])
    if result
      json_response(result.create_json_object(request.host), :ok)
    else
      json_response({message: 'Not found'}, :not_found)
    end
  end

  def destroy
    result = ShortenedUrl.find_by(unique_key: params[:unique_key])
    if result
      result.delete
      json_response({message: 'Successfully Deleted'}, :ok)
    else
      json_response({message: 'Not found'}, :not_found)
    end
  end

  private
    def url_shortener_params
      params.require(:url_shortener).permit(:url)
    end

    # cleaning the url
    def sanitize_url
      @sanitized_url = UrlShortener.sanitize_url(url_shortener_params[:url])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :sanitize_url, only: [:create]

  def index
    @shortened_urls = ShortenedUrl.all.select(:url, :unique_key)
  end


  def new
    @shortened_url = ShortenedUrl.new
  end

  def create
    @shortened_url = ShortenedUrl.find_or_create_by(url: @sanitized_url)
    respond_to do |format|
      if @shortened_url.present?
        format.html { redirect_to shortened_urls_path, notice: 'Shortened url was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @shortened_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_from_csv
    CSV.foreach(params[:csv].tempfile, headers: true) do |row|
      sanitized_url = UrlShortener.sanitize_url(row.to_h["url"])
      ShortenedUrl.find_or_create_by(url: sanitized_url)
    end
    redirect_to shortened_urls_path, notice: 'Shortened urls were successfully created.'
    # respond_to do |format|
    #   if @shortenf ed_url.present?
    #     format.html { redirect_to shortened_urls_path, notice: 'Shortened urls were successfully created.' }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @shortened_url.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def redirect_handler
    record = ShortenedUrl.find_by_unique_key(params[:unique_key])
    redirect_url = (record && record.url ? record.url : root_path)
    redirect_to redirect_url
  end

  private
    def shortened_url_params
      params.fetch(:shortened_url, {})
    end

    # cleaning the url
    def sanitize_url
      @sanitized_url = UrlShortener.sanitize_url(shortened_url_params[:url])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end

    rescue_from ActiveRecord::RecordNotUnique do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/helpers/response_helper.rb
module ResponseHelper
	def json_response(object, status = :ok)
		render json: object, status: status
	end
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end

  def create_url(host, uniq_key)
    "#{host}/#{uniq_key}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">URL Shortener</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if params[:action].eql?('index') %>">
            <a class="nav-link" href="<%= shortened_urls_path %>">All urls <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item <%= 'active' if params[:action].eql?('new') %>">
            <a class="nav-link" href="<%= new_shortened_url_path %>">Create New</a>
          </li>
          <li class="nav-item <%= 'active' if params[:action].eql?('upload_from_csv') %>">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#upload-csv-modal">Upload From CSV</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="container mt-50">
        <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %>">
              <%= value %>
            </div>
        <% end %>
      </div>
      <div class="container mt-50">
        <%= yield %>
      </div>
    </div>
    <%= render partial: 'shortened_urls/upload_from_csv' %>
  </body>
</html>

app/views/shortened_urls/_form.html.erb
<%= form_with(model: shortened_url, local: true) do |form| %>
  <% if shortened_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shortened_url.errors.count, "error") %> prohibited this shortened_url from being saved:</h2>

      <ul>
      <% shortened_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :url, placeholder: 'Enter url', class: 'form-control', required: true %>
  </div>

  <div class="actions">
    <%= button_tag 'Submit', type: 'submit', class: 'btn btn-primary pull-right'  %>
  </div>
<% end %>

app/views/shortened_urls/_upload_from_csv.html.erb
<!-- Modal -->
<div class="modal fade" id="upload-csv-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag upload_from_csv_shortened_urls_path, method: :post, multipart: true do %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Create from CSV</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <%= file_field_tag 'Upload a csv', required: true, class: 'form-control', name: 'csv' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= button_tag 'Submit', class: 'btn btn-primary', type: 'submit' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shortened_urls/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Original url</th>
      <th>Short url</th>
    </tr>
  </thead>

  <tbody>
    <% @shortened_urls.each do |shortened_url| %>
      <tr>
        <td><%= link_to "#{shortened_url.url}", "#{shortened_url.url}", target: '_blank' %></td>
        <td><%= link_to "#{create_url(request.host, shortened_url.unique_key)}", "/#{shortened_url.unique_key}", target: '_blank' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to new_shortened_url_path do %>
    <!--<button type="button" class="btn btn-success">New Link</button>-->
<%# end %>

app/views/shortened_urls/new.html.erb
<div class="row justify-content-md-center">
  <div class="col-6">
    <p class="head-text">Create a new short URL</p>
    <%= render 'form', shortened_url: @shortened_url %>
  </div>
</div>